package models;
// Generated Oct 6, 2012 2:33:08 AM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Games generated by hbm2java
 */
@Entity
@Table(name = "Games")
public class Games {

	@Id
	@Column(name = "id")
	@GeneratedValue
     private int id;
	
	@Column(name = "game_name")
     private String gameName;
	
	@Column(name = "added")
    private Date added;

    public Games() {
    }

    public Games(int id, String gameName, Date added) {
       this.id = id;
       this.gameName = gameName;
       this.added = added;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getGameName() {
        return this.gameName;
    }
    
    public void setGameName(String gameName) {
        this.gameName = gameName;
    }
    public Date getAdded() {
        return this.added;
    }
    
    public void setAdded(Date added) {
        this.added = added;
    }




}


