package models;
// Generated Oct 6, 2012 2:33:08 AM by Hibernate Tools 3.4.0.CR1



/**
 * RolesUsersId generated by hbm2java
 */
public class RolesUsersId  implements java.io.Serializable {


     private int userId;
     private int roleId;

    public RolesUsersId() {
    }

    public RolesUsersId(int userId, int roleId) {
       this.userId = userId;
       this.roleId = roleId;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public int getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RolesUsersId) ) return false;
		 RolesUsersId castOther = ( RolesUsersId ) other; 
         
		 return (this.getUserId()==castOther.getUserId())
 && (this.getRoleId()==castOther.getRoleId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserId();
         result = 37 * result + this.getRoleId();
         return result;
   }   


}


