package models;
// Generated Oct 6, 2012 2:33:08 AM by Hibernate Tools 3.4.0.CR1



/**
 * RolesUsers generated by hbm2java
 */
public class RolesUsers  implements java.io.Serializable {


     private RolesUsersId id;

    public RolesUsers() {
    }

    public RolesUsers(RolesUsersId id) {
       this.id = id;
    }
   
    public RolesUsersId getId() {
        return this.id;
    }
    
    public void setId(RolesUsersId id) {
        this.id = id;
    }




}


