package models;
// Generated Oct 6, 2012 2:33:08 AM by Hibernate Tools 3.4.0.CR1



/**
 * Sessions generated by hbm2java
 */
public class Sessions  implements java.io.Serializable {


     private String sessionId;
     private int lastActive;
     private String contents;

    public Sessions() {
    }

    public Sessions(String sessionId, int lastActive, String contents) {
       this.sessionId = sessionId;
       this.lastActive = lastActive;
       this.contents = contents;
    }
   
    public String getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }
    public int getLastActive() {
        return this.lastActive;
    }
    
    public void setLastActive(int lastActive) {
        this.lastActive = lastActive;
    }
    public String getContents() {
        return this.contents;
    }
    
    public void setContents(String contents) {
        this.contents = contents;
    }




}


