package models;
// Generated Oct 6, 2012 2:33:08 AM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "Users")
public class Users  implements java.io.Serializable {
	
	
	
	@Id
	@Column(name = "id")
	@GeneratedValue
     private Integer id;
	
	@Column(name = "email")
     private String email;
	@Column(name = "username")
     private String username;
	@Column(name = "first_name")
     private String firstName;
	@Column(name = "surname")
     private String surname;
	@Column(name = "password")
     private String password;
	@Column(name = "logins")
     private int logins;
	@Column(name = "last_login")
     private Integer lastLogin;
	@Column(name = "reser_token")
     private String resetToken;
	@Column(name = "registered")
     private Date registered;
	@Column(name = "balance")
     private int balance;
	@Column(name = "last_game_palyed")
     private Date lastGamePlayed;
	

    public Users() {
    }

	
    public Users(String email, String username, String firstName, String password, int logins, Date registered, int balance) {
        this.email = email;
        this.username = username;
        this.firstName = firstName;
        this.password = password;
        this.logins = logins;
        this.registered = registered;
        this.balance = balance;
    }
    public Users(String email, String username, String firstName, String surname, String password, int logins, Integer lastLogin, String resetToken, Date registered, int balance, Date lastGamePlayed, Set userTokenses) {
       this.email = email;
       this.username = username;
       this.firstName = firstName;
       this.surname = surname;
       this.password = password;
       this.logins = logins;
       this.lastLogin = lastLogin;
       this.resetToken = resetToken;
       this.registered = registered;
       this.balance = balance;
       this.lastGamePlayed = lastGamePlayed;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public int getLogins() {
        return this.logins;
    }
    
    public void setLogins(int logins) {
        this.logins = logins;
    }
    public Integer getLastLogin() {
        return this.lastLogin;
    }
    
    public void setLastLogin(Integer lastLogin) {
        this.lastLogin = lastLogin;
    }
    public String getResetToken() {
        return this.resetToken;
    }
    
    public void setResetToken(String resetToken) {
        this.resetToken = resetToken;
    }
    public Date getRegistered() {
        return this.registered;
    }
    
    public void setRegistered(Date registered) {
        this.registered = registered;
    }
    public int getBalance() {
        return this.balance;
    }
    
    public void setBalance(int balance) {
        this.balance = balance;
    }
    public Date getLastGamePlayed() {
        return this.lastGamePlayed;
    }
    
    public void setLastGamePlayed(Date lastGamePlayed) {
        this.lastGamePlayed = lastGamePlayed;
    }




}


